#!/usr/bin/env python3
"""Generate the Webots world from the YAML configs (single source of truth).

Produces:
  webots/worlds/textures/ground.png   -- rasterized synthetic ground function
  webots/protos/FourCameraRover.proto -- robot with the 4 configured cameras
  webots/worlds/bev_test_world.wbt    -- flat arena + obstacles + rover

Only Webots base nodes are used (no network EXTERNPROTO downloads). The
ground texture uses an emissive map so rendered colors are lighting-
independent and match the synthetic oracle.

Texture/plane mapping: see _write_ground_texture (pinned by the WB3 test).
"""
from __future__ import annotations

import sys
from pathlib import Path

import cv2
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from bev.camera_model import rotation_vehicle_to_camera  # noqa: E402
from bev.synthetic import ground_color  # noqa: E402
from configs_schema import (  # noqa: E402
    CamerasConfig,
    SceneConfig,
    load_yaml_config,
)

WORLDS = PROJECT_ROOT / "webots" / "worlds"
PROTOS = PROJECT_ROOT / "webots" / "protos"
GROUND_SIZE_M = 24.0
GROUND_PX_PER_M = 100  # 1 cm/px

WEBOTS_VERSION = "R2025a"


def _axis_angle(rot: np.ndarray) -> tuple[float, float, float, float]:
    """Rotation matrix -> Webots SFRotation (axis x y z, angle rad)."""
    angle = float(np.arccos(np.clip((np.trace(rot) - 1.0) / 2.0, -1.0, 1.0)))
    if angle < 1e-9:
        return 0.0, 0.0, 1.0, 0.0
    if abs(angle - np.pi) < 1e-6:
        # axis from the largest diagonal element of (R + I) / 2
        m = (rot + np.eye(3)) / 2.0
        axis = np.sqrt(np.maximum(np.diag(m), 0.0))
        axis[1] = np.copysign(axis[1], m[0, 1])
        axis[2] = np.copysign(axis[2], m[0, 2])
    else:
        axis = np.array(
            [rot[2, 1] - rot[1, 2], rot[0, 2] - rot[2, 0], rot[1, 0] - rot[0, 1]]
        ) / (2.0 * np.sin(angle))
    axis = axis / np.linalg.norm(axis)
    return float(axis[0]), float(axis[1]), float(axis[2]), angle


def _camera_body_rotation(yaw_deg: float, pitch_deg: float, roll_deg: float) -> np.ndarray:
    """Camera BODY (FLU, +x optical) orientation in the vehicle frame.

    Webots cameras look along their +x with +y left / +z up — exactly our
    body convention, so the node rotation is R_body_to_vehicle. Reuse the
    pinned math: rotation_vehicle_to_camera = AXIS_SWITCH @ R_b2v.T.
    """
    axis_switch = np.array([[0.0, -1.0, 0.0], [0.0, 0.0, -1.0], [1.0, 0.0, 0.0]])
    r_v2c = rotation_vehicle_to_camera(yaw_deg, pitch_deg, roll_deg)
    return (axis_switch.T @ r_v2c).T  # R_b2v


def _write_ground_texture(scene: SceneConfig, out: Path) -> None:
    """Webots maps a Plane texture with image-u along world +X and image-v
    (top to bottom) along world -Y (verified empirically against the axis
    markers, pinned by the WB3 integration test):
        world X = -S/2 + (col + 0.5)/px_per_m
        world Y = +S/2 - (row + 0.5)/px_per_m
    """
    n = int(GROUND_SIZE_M * GROUND_PX_PER_M)
    half = GROUND_SIZE_M / 2.0
    x_of_col = -half + (np.arange(n) + 0.5) / GROUND_PX_PER_M
    y_of_row = half - (np.arange(n) + 0.5) / GROUND_PX_PER_M
    grid_y, grid_x = np.meshgrid(y_of_row, x_of_col, indexing="ij")
    img = ground_color(grid_x, grid_y, scene)
    out.parent.mkdir(parents=True, exist_ok=True)
    cv2.imwrite(str(out), img)


def _proto_text(cams: CamerasConfig) -> str:
    cam_nodes = []
    for name, c in cams.cameras.items():
        ax, ay, az, ang = _axis_angle(_camera_body_rotation(c.yaw_deg, c.pitch_deg, c.roll_deg))
        fov = np.deg2rad(c.fov_deg)
        cam_nodes.append(f"""    Camera {{
      name "{name}"
      translation {c.x} {c.y} {c.z}
      rotation {ax:.9f} {ay:.9f} {az:.9f} {ang:.9f}
      fieldOfView {fov:.9f}
      width {c.width}
      height {c.height}
    }}""")
    cameras = "\n".join(cam_nodes)
    return f"""#VRML_SIM {WEBOTS_VERSION} utf8
# Generated by scripts/gen_webots.py from config/cameras.yaml — do not edit.
PROTO FourCameraRover [
  field SFVec3f    translation 0 0 0
  field SFRotation rotation    0 0 1 0
  field SFString   controller  "<extern>"
]
{{
  Robot {{
    translation IS translation
    rotation IS rotation
    controller IS controller
    name "rover"
    children [
      Pose {{
        translation 0 0 0.22
        children [
          Shape {{
            appearance PBRAppearance {{ baseColor 0.15 0.25 0.55 roughness 0.8 metalness 0 }}
            geometry Box {{ size 0.9 0.6 0.38 }}
          }}
        ]
      }}
{cameras}
    ]
  }}
}}
"""


def _obstacle_nodes(scene: SceneConfig) -> str:
    nodes = []
    for i, o in enumerate(scene.obstacles):
        b, g, r = (v / 255.0 for v in o.color)
        nodes.append(f"""Solid {{
  name "obstacle_{i}_{o.type}"
  translation {o.x} {o.y} {o.size_z / 2.0}
  children [
    Shape {{
      appearance PBRAppearance {{
        baseColor 0 0 0
        emissiveColor {r:.4f} {g:.4f} {b:.4f}
        roughness 1
        metalness 0
      }}
      geometry Box {{ size {o.size_x} {o.size_y} {o.size_z} }}
    }}
  ]
}}""")
    return "\n".join(nodes)


def _world_text(scene: SceneConfig) -> str:
    return f"""#VRML_SIM {WEBOTS_VERSION} utf8
# Generated by scripts/gen_webots.py from config/scene.yaml — do not edit.
EXTERNPROTO "../protos/FourCameraRover.proto"

WorldInfo {{
  basicTimeStep 32
  coordinateSystem "ENU"
}}
Viewpoint {{
  orientation 0.25 0.43 -0.87 1.9
  position 6.5 7.5 6.0
}}
Background {{
  skyColor [ 0.27 0.51 0.71 ]
}}
DirectionalLight {{
  direction -0.3 -0.4 -1
  intensity 1.6
  castShadows FALSE
}}
Solid {{
  name "ground"
  children [
    Shape {{
      appearance PBRAppearance {{
        baseColor 0 0 0
        emissiveColorMap ImageTexture {{ url [ "textures/ground.png" ] }}
        roughness 1
        metalness 0
      }}
      geometry Plane {{ size {GROUND_SIZE_M} {GROUND_SIZE_M} }}
    }}
  ]
}}
{_obstacle_nodes(scene)}
FourCameraRover {{
}}
"""


def main() -> None:
    cfg_dir = PROJECT_ROOT / "config"
    cams = load_yaml_config(cfg_dir / "cameras.yaml", CamerasConfig)
    scene = load_yaml_config(cfg_dir / "scene.yaml", SceneConfig)

    _write_ground_texture(scene, WORLDS / "textures" / "ground.png")
    PROTOS.mkdir(parents=True, exist_ok=True)
    (PROTOS / "FourCameraRover.proto").write_text(_proto_text(cams))
    WORLDS.mkdir(parents=True, exist_ok=True)
    (WORLDS / "bev_test_world.wbt").write_text(_world_text(scene))
    print(f"wrote {WORLDS / 'bev_test_world.wbt'}")
    print(f"wrote {PROTOS / 'FourCameraRover.proto'}")
    print(f"wrote {WORLDS / 'textures' / 'ground.png'}")


if __name__ == "__main__":
    main()
